mysql:
  image: ncsu/mysql
  expose:
    - "3306"
  ports:
    - "3307:3306"
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: yes
    MYSQL_DATABASE: itrust

web:
  image: ncsu/itrust
  ports:
    - "8888:8080"
  links:
    - mysql:mysql
